### ISSUE TITLE
MySQL server has gone away

### ISSUE THREAD

**Issue by ondrejhlavacek** [keboola/db-writer-mysql#23]
retry?

```
#0 /code/vendor/keboola/db-writer-common/src/Application.php(62): Keboola\\DbWriter\\Application->runAction()
#1 /code/run.php(49): Keboola\\DbWriter\\Application->run()\n#2 {main}
```

https://connection.eu-central-1.keboola.com/admin/utils/logs?file=2019/01/17/10/2019-01-17-10-24-37-5c4049d570df9-exception

https://connection.eu-central-1.keboola.com/admin/utils/logs?file=2019/01/17/10/2019-01-17-10-24-37-5c4049d57b65b-log

**Comment by yustme** [comment]
Retry + user error pokud se to nepodaří. 

https://keboola.slack.com/archives/C09U3R1J4/p1551792370010300

**Comment by ujovlado** [comment]
https://keboola.slack.com/archives/C09U3R1J4/p1561632164014800

**Comment by Halama** [comment]
Dnes začalo dělat na projektu `2612` opakovaně https://keboola.slack.com/archives/C09U3R1J4/p1572853631015000
